packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  postcss: '^8.5.23'
  tar: '^7.5.22'
  '@xmldom/xmldom': '^0.9.12'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'cypress'
  - 'nx'
  - 'sharp'
  - 'unrs-resolver'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  'cypress': true
  'nx': true
  'sharp': true
  'unrs-resolver': true
